2019-07-20 05:04:06,719 INFO - log_helper - Finished configuring logger
2019-07-20 05:04:09,313 CRITICAL - log_helper - Unhandled exception
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    logger = maml.run(args, log_interval=100, rerun=True)
  File "/home/tj/cavia_context/regression/maml.py", line 198, in run
    logger.print_info(i_iter, start_time)
  File "/home/tj/cavia_context/regression/logger.py", line 37, in print_info
    _logger.info(
NameError: name '_logger' is not defined
